### ISSUE TITLE
Brew Doctor `warning on ruby file`

### ISSUE THREAD

**Issue by BenjaminHCCarr** [beeftornado/homebrew-rmtree#13] opened 2017-01-03 20:31 UTC
Thanks so much for this script; unfortunately tapping you is now making `brew doctor` unhappy:
```
Warning: Found Ruby file outside beeftornado/rmtree tap formula directory
(/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/Formula):
  /usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/brew-rmtree.rb
```

I don't know if it is a filename collision:
find output:
```
./brew-rmtree.rb
./Formula
./Formula/brew-rmtree.rb
./LICENSE
./README.md
```
or just the fact that your script is ruby, which seems odd.

Possibly @MikeMcQuaid or @vitorgalvao who has:
https://github.com/vitorgalvao/homebrew-tiny-scripts/
with a ton of ruby scripts can tell us why this is erroring?

**Comment by MikeMcQuaid** [comment] 2017-01-03 21:00
The issue is having a `Formula` directory and a Ruby file in the repository root (where formula can also be read) meaning it's ambiguous for Homebrew where the formulae are. The root Ruby file should go in a different directory. Ideally, though, this would just be handled as a Homebrew Tap external command like `brew services`:  https://github.com/Homebrew/homebrew-services/tree/master/cmd

**Comment by BenjaminHCCarr** [comment] 2017-01-03 21:08
@MikeMcQuaid okay, makes total sense, so @beeftornado should do what many of us have done which is something like: https://github.com/BenjaminHCCarr/homebrew-tap

**Comment by lanox** [comment] 2017-01-13 04:33
so is there anything to do here ?  I am getting the same warning as well. ?

**Comment by beeftornado** [comment] 2017-01-13 04:36
I'll look into this

**Comment by beeftornado** [comment] 2017-01-13 04:38
#11 might take care of this. Let me test and merge tonight

**Comment by beeftornado** [comment] 2017-01-13 04:57
I merged #11, which should fix this issue. Can someone update and post back if it resolves for them or not? I read when caskroom made the switch some users actually had to uninstall brew-cask, not sure if our users will need to do that as well, thanks for being the guinea pigs :)

**Comment by jsfaint** [comment] 2017-01-13 05:44
@beeftornado yes, the installed rmtree must be uninstalled.
With that PR, the only thing we need is `brew tap beeftornado/rmtree` for using `rmtree`

**Comment by beeftornado** [comment] 2017-01-13 05:45
@jsfaint Yeah, just updated the readme, thanks!

**Comment by michel-kraemer** [comment] 2017-01-14 09:39
@beeftornado  Thanks for the update. I did the following:

    brew uninstall brew-rmtree
    brew untap beeftornado/rmtree
    brew tap beeftornado/rmtree

And now the warning is gone. Thanks!

**Closed** 2017-02-16 05:10 UTC
