### ISSUE TITLE
Transitive dependencies not uninstalled in correct order

### ISSUE THREAD

**Issue by irundaia** [beeftornado/homebrew-rmtree#14] opened 2017-01-06 07:59 UTC
I've had gnupg2 installed for quite some time and I wanted to remove it. So I called `brew rmtree gnupg2`.

This listed the following dependencies:
```
Can safely be removed
----------------------
dirmngr
gpg-agent
libassuan
libgcrypt
libgpg-error
libksba
libusb
libusb-compat
pinentry
pth
```
After accepting the uninstallation of all these packages, brew failed to uninstall several dependencies because they were needed for some dependencies in this list. For instance, it started with uninstalling `libgpg-error`, which was still required for dirmngr. Below I've attached the log of the first run of `brew rmtree` (I've used it to also uninstall the refused formulae after the first run).

```
Uninstalling /usr/local/Cellar/gnupg2/2.0.30_2... (91 files, 3.7M)

Error: Refusing to uninstall /usr/local/Cellar/libgpg-error/1.26
because it is required by dirmngr, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies libgpg-error


Error: Refusing to uninstall /usr/local/Cellar/libgcrypt/1.7.5
because it is required by dirmngr, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies libgcrypt


Error: Refusing to uninstall /usr/local/Cellar/libksba/1.3.5
because it is required by dirmngr, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies libksba


Error: Refusing to uninstall /usr/local/Cellar/libassuan/2.4.3_1
because it is required by dirmngr, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies libassuan


Error: Refusing to uninstall /usr/local/Cellar/pinentry/0.9.7
because it is required by gpg-agent, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies pinentry


Error: Refusing to uninstall /usr/local/Cellar/pth/2.0.7
because it is required by dirmngr, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies pth


Uninstalling /usr/local/Cellar/gpg-agent/2.0.30_1... (11 files, 695.6K)

Uninstalling /usr/local/Cellar/dirmngr/1.1.1_2... (66 files, 527.6K)

Error: Refusing to uninstall /usr/local/Cellar/libusb/1.0.20
because it is required by libusb-compat, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies libusb


Uninstalling /usr/local/Cellar/libusb-compat/0.1.5... (13 files, 93.3K)
```

**Comment by Argon-** [comment] 2017-01-06 11:35
Unfortunately this repo seems to be dead/inactive. I guess it's best to settle for one of the forks to continue, e.g. https://github.com/jsfaint/homebrew-rmtree as it solves the (as of now probably most important) problem explained in https://github.com/beeftornado/homebrew-rmtree/pull/11

**Comment by irundaia** [comment] 2017-01-06 12:36
This issue is also a problem in the linked repo. I'll create an issue there as well

**Comment by ilovezfs** [comment] 2017-01-06 15:12
If you `export HOMEBREW_DEVELOPER=1` the errors will be warnings so it at least won't go 💥

**Comment by beeftornado** [comment] 2017-01-13 05:36
Thanks for reporting this, and thanks for the detailed example. I'll look into this

**Comment by jsfaint** [comment] 2017-01-13 05:37
Hi @Argon- My PR was already merged by @beeftornado 
Thanks @beeftornado  😄

**Comment by metakirby5** [comment] 2017-01-23 23:39
I got around this by adding the `--ignore-dependencies` flag to [this line](https://github.com/beeftornado/homebrew-rmtree/blob/0ea3a76f33c4317e2e3fcb7effb3fa1eb9dfa707/cmd/brew-rmtree.rb#L113). I'm not sure if this is a "clean" solution, but it seems to have worked for me.

**Comment by irundaia** [comment] 2017-01-25 12:17
@metakirby5 Doesn't this mean that the dependencies aren't removed?

**Comment by ilovezfs** [comment] 2017-01-25 12:26
No.

If HOMEBREW_DEVELOPER is not set, and there are reverse dependencies using a formula, brew will error out if you try to remove that formula. `--ignore-dependencies` will suppress the error.

If HOMEBREW_DEVELOPER is set, and there are reverse dependencies using a formula, brew will issue a warning if you try to remove that formula. `--ignore-dependencies` will suppress the warning.

The fact that rmtree needs to use `--ignore-dependencies` means that it is in fact removing things that have reverse dependencies.

**Comment by irundaia** [comment] 2017-01-25 14:16
I'm not sure if this will be the behaviour I'm looking for though, as this might uninstall packages that might be needed for other packages.

**Comment by ilovezfs** [comment] 2017-01-25 14:33
@irundaia theoretically it should be fine because the cause is that the packages are being removed in the "wrong" order instead of all at once or in the "right" order. The "correct" fix here is to remove them in a single call to brew uninstall, "brew uninstall A B C D" or to the uninstalls in an order that always removes a reverse dependency before its dependencies.

**Comment by ggPeti** [comment] 2017-02-23 22:07
In the meantime I put together a quick hack to recursively remove dependencies. Check it out: https://github.com/ggPeti/homebrew-rmrec

**Comment by irundaia** [comment] 2017-02-24 15:29
@ggPeti, I've tested your work, it seems to work fine :) It does seem to be a tad slow tbh. But I can deal with that. :)

**Comment by beeftornado** [comment] 2017-12-14 01:48
Related to #21 #24

**Closed** 2018-01-29 04:32 UTC
