### ISSUE TITLE
Error: undefined method `default_formula' for #<MacOSRequirement: "macos" [:mountain_lion]>

### ISSUE THREAD

**Issue by shrx** [beeftornado/homebrew-rmtree#26] opened 2018-01-19 23:06 UTC
Got this error (for several packages):

```
brew rmtree gphoto2
Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:125:in `uses'
Please report this to the beeftornado/rmtree tap!

Error: undefined method `default_formula' for #<MacOSRequirement: "macos" [:mountain_lion]>
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:145:in `block (3 levels) in uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:145:in `any?'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:145:in `block (2 levels) in uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:126:in `each'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:126:in `all?'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:126:in `block in uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:125:in `select'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:125:in `uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:332:in `rmtree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:401:in `block in main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:401:in `each'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:401:in `main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:405:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:106:in `<main>'
```

**Comment by heychirag** [comment] 2018-01-20 17:28
I guess this is a duplicate of #20 which was fixed by #22. Try updating homebrew and/or its taps.

**Comment by leepowellcouk** [comment] 2018-01-22 08:35
Getting similar:

brew rmtree --force php56
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/bin/brew-rmtree.rb:45:in `<module:BrewRmtree>'

==> Examining installed formulae required by php56...
 -  0 / 10 Error: undefined method `default_formula' for #<PharRequirement: "phar" []>
/usr/local/bin/brew-rmtree.rb:146:in `block (3 levels) in uses'
/usr/local/bin/brew-rmtree.rb:146:in `any?'
/usr/local/bin/brew-rmtree.rb:146:in `block (2 levels) in uses'
/usr/local/bin/brew-rmtree.rb:127:in `each'
/usr/local/bin/brew-rmtree.rb:127:in `all?'
/usr/local/bin/brew-rmtree.rb:127:in `block in uses'
/usr/local/bin/brew-rmtree.rb:126:in `select'
/usr/local/bin/brew-rmtree.rb:126:in `uses'
/usr/local/bin/brew-rmtree.rb:175:in `used_by'
/usr/local/bin/brew-rmtree.rb:183:in `still_used_by'
/usr/local/bin/brew-rmtree.rb:294:in `block (2 levels) in build_tree'
/usr/local/bin/brew-rmtree.rb:287:in `each'
/usr/local/bin/brew-rmtree.rb:287:in `block in build_tree'
/usr/local/bin/brew-rmtree.rb:101:in `show_wait_spinner'
/usr/local/bin/brew-rmtree.rb:275:in `build_tree'
/usr/local/bin/brew-rmtree.rb:336:in `rmtree'
/usr/local/bin/brew-rmtree.rb:391:in `block in main'
/usr/local/bin/brew-rmtree.rb:391:in `each'
/usr/local/bin/brew-rmtree.rb:391:in `main'
/usr/local/bin/brew-rmtree.rb:395:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:106:in `<main>'

**Comment by shaunxu** [comment] 2018-01-23 03:47
Same here

```
➜  ~ brew rmtree graphviz
Error: undefined method `default_formula' for #<MacOSRequirement: "macos" [:mountain_lion]>
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:145:in `block (3 levels) in uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:145:in `any?'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:145:in `block (2 levels) in uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:126:in `each'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:126:in `all?'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:126:in `block in uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:125:in `select'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:125:in `uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:332:in `rmtree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:401:in `block in main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:401:in `each'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:401:in `main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:405:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:106:in `<main>'
```

**Comment by warpedgeoid** [comment] 2018-01-25 16:14
Yep! No joy, here, either.

**Comment by tobylunt** [comment] 2018-01-26 18:59
similar for me but X11

```
Error: undefined method `default_formula' for #<X11Requirement: "x11" [:optional]>
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:145:in `block (3 levels) in uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:145:in `any?'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:145:in `block (2 levels) in uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:126:in `each'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:126:in `all?'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:126:in `block in uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:125:in `select'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:125:in `uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:332:in `rmtree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:401:in `block in main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:401:in `each'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:401:in `main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:405:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:106:in `<main>'
```

**Closed** 2018-01-29 04:30 UTC
Labels: bug
