### ISSUE TITLE
undefined method `uses_args' for Homebrew:Module

### ISSUE THREAD

**Issue by raffaelewylde** [beeftornado/homebrew-rmtree#61] opened 2024-04-21 20:42 UTC
Hey, just tried running rmtree and got the following error.
```
Error: undefined method `uses_args' for Homebrew:Module
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:191:in `block (2 levels) in uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:148:in `all?'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:148:in `block in uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:147:in `select'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:147:in `uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:448:in `rmtree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:565:in `block in main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:565:in `each'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:565:in `main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:569:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:10:in `require'
/usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:10:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/beeftornado/homebrew-rmtree/issues/new
```
output of brew config is 
```
HOMEBREW_VERSION: 4.2.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9edabf02ce29e54d0b717baa757cff38ad0c0e25
Last commit: 7 days ago
Core tap JSON: 21 Apr 20:22 UTC
Core cask tap JSON: 21 Apr 20:22 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT_THEME: Monokai Extended
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.tNC5riRiCh/org.xquartz:0
HOMEBREW_EDITOR: nvim not found
HOMEBREW_EVAL_ALL: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 14.0.0 build 1400
Git: 2.44.0 => /usr/local/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 12.7.4-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
```
Running rmtree with --debug doesn't give any more info really, it's the same error text exactly plus a giant list of all my installed formulas  from APILoader.

I'm running MacOS Monterey 12.7.4. 

Let me know if any other info would be helpful.

**Comment by boris1993** [comment] 2024-05-06 14:32
Looks like a duplicate of #60

**Closed** 2024-05-06 20:04 UTC
